[package]
name = "whyhttp"
version = "0.1.0"
edition = "2024"
description = "HTTP mock server for use in tests. Starts a real server, expectations configured via fluent builder API, verified automatically on drop."
license = "MIT"
repository = "https://github.com/nerjs/whyhttp"
readme = "README.md"
keywords = ["http", "mock", "test", "server", "testing"]
categories = ["development-tools::testing", "network-programming"]
include = ["src/**", "README.md", "LICENSE"]


[dependencies]
tiny_http = "0.12.0"

[dev-dependencies]
rstest = "0.26.1"
tokio = { version = "1.50.0", features = ["full"] }
reqwest = { version = "0.13.2", features = ["blocking"] }
