//! Integration tests for all shorthand helper methods generated by impl_helpers!.
//! Each test shows one shorthand in minimal working usage.

use reqwest::blocking::Client;
use whyhttp::Whyhttp;

fn client() -> Client {
    Client::new()
}

// ── when_* on Whyhttp ─────────────────────────────────────────────────────────

#[test]
fn when_path() {
    let server = Whyhttp::run();
    server.when_path("/greet").response().status(200u16);
    client()
        .get(format!("{}/greet", server.url()))
        .send()
        .unwrap();
}

#[test]
fn when_method() {
    let server = Whyhttp::run();
    server.when_method("DELETE").response().status(204u16);
    let resp = client().delete(server.url()).send().unwrap();
    assert_eq!(resp.status().as_u16(), 204);
}

#[test]
fn when_query() {
    let server = Whyhttp::run();
    server.when_query("sort", "asc").response().status(200u16);
    client()
        .get(format!("{}/?sort=asc", server.url()))
        .send()
        .unwrap();
}

#[test]
fn when_query_exists() {
    let server = Whyhttp::run();
    server.when_query_exists("filter").response().status(200u16);
    client()
        .get(format!("{}/?filter=active", server.url()))
        .send()
        .unwrap();
}

#[test]
fn when_without_query() {
    let server = Whyhttp::run();
    server.when_without_query("debug").response().status(200u16);
    client().get(server.url()).send().unwrap();
}

#[test]
fn when_header() {
    let server = Whyhttp::run();
    server
        .when_header("x-version", "2")
        .response()
        .status(200u16);
    client()
        .get(server.url())
        .header("x-version", "2")
        .send()
        .unwrap();
}

#[test]
fn when_header_exists() {
    let server = Whyhttp::run();
    server
        .when_header_exists("x-request-id")
        .response()
        .status(200u16);
    client()
        .get(server.url())
        .header("x-request-id", "123")
        .send()
        .unwrap();
}

#[test]
fn when_without_header() {
    let server = Whyhttp::run();
    server
        .when_without_header("x-internal")
        .response()
        .status(200u16);
    client().get(server.url()).send().unwrap();
}

#[test]
fn when_body() {
    let server = Whyhttp::run();
    server.when_body("data").response().status(200u16);
    client().post(server.url()).body("data").send().unwrap();
}

#[test]
fn when_without_body() {
    let server = Whyhttp::run();
    server.when_without_body().response().status(200u16);
    client().get(server.url()).send().unwrap();
}

// ── should_* on Whyhttp ───────────────────────────────────────────────────────

#[test]
fn should_path() {
    let server = Whyhttp::run();
    server.should_path("/check").response().status(200u16);
    client()
        .get(format!("{}/check", server.url()))
        .send()
        .unwrap();
}

#[test]
fn should_method() {
    let server = Whyhttp::run();
    server.should_method("GET").response().status(200u16);
    client().get(server.url()).send().unwrap();
}

#[test]
fn should_query() {
    let server = Whyhttp::run();
    server.should_query("q", "test").response().status(200u16);
    client()
        .get(format!("{}/?q=test", server.url()))
        .send()
        .unwrap();
}

#[test]
fn should_query_exists() {
    let server = Whyhttp::run();
    server.should_query_exists("page").response().status(200u16);
    client()
        .get(format!("{}/?page=1", server.url()))
        .send()
        .unwrap();
}

#[test]
fn should_without_query() {
    let server = Whyhttp::run();
    server
        .should_without_query("internal")
        .response()
        .status(200u16);
    client().get(server.url()).send().unwrap();
}

#[test]
fn should_header() {
    let server = Whyhttp::run();
    server
        .should_header("x-token", "abc")
        .response()
        .status(200u16);
    client()
        .get(server.url())
        .header("x-token", "abc")
        .send()
        .unwrap();
}

#[test]
fn should_header_exists() {
    let server = Whyhttp::run();
    server
        .should_header_exists("authorization")
        .response()
        .status(200u16);
    client()
        .get(server.url())
        .header("authorization", "Bearer x")
        .send()
        .unwrap();
}

#[test]
fn should_without_header() {
    let server = Whyhttp::run();
    server
        .should_without_header("x-debug")
        .response()
        .status(200u16);
    client().get(server.url()).send().unwrap();
}

#[test]
fn should_body() {
    let server = Whyhttp::run();
    server.should_body("ping").response().status(200u16);
    // POST is used only because reqwest needs a body-capable method
    client().post(server.url()).body("ping").send().unwrap();
}

#[test]
fn should_without_body() {
    let server = Whyhttp::run();
    server.should_without_body().response().status(200u16);
    client().get(server.url()).send().unwrap();
}

#[test]
fn should_times() {
    let server = Whyhttp::run();
    server
        .when_path("/hit")
        .should_times(3u16)
        .response()
        .status(200u16);
    for _ in 0..3 {
        client()
            .get(format!("{}/hit", server.url()))
            .send()
            .unwrap();
    }
}

// ── response_* on Whyhttp ─────────────────────────────────────────────────────

#[test]
fn response_status() {
    let server = Whyhttp::run();
    server.response_status(418u16);
    let resp = client().get(server.url()).send().unwrap();
    assert_eq!(resp.status().as_u16(), 418);
}

#[test]
fn response_header() {
    let server = Whyhttp::run();
    server.response_header("x-custom", "yes");
    let resp = client().get(server.url()).send().unwrap();
    assert_eq!(
        resp.headers().get("x-custom").and_then(|v| v.to_str().ok()),
        Some("yes")
    );
}

#[test]
fn response_body() {
    let server = Whyhttp::run();
    server.response_body("pong");
    let resp = client().get(server.url()).send().unwrap();
    assert_eq!(resp.text().unwrap(), "pong");
}

// ── when_* / should_* / response_* on builder types ─────────────────────────

#[test]
fn when_path_from_response_builder() {
    // when_path is also available on WhyhttpResponse (starts a new expectation)
    let server = Whyhttp::run();
    server
        .when_path("/first")
        .response()
        .status(200u16)
        .when_path("/second")
        .response()
        .status(201u16);

    let r1 = client()
        .get(format!("{}/first", server.url()))
        .send()
        .unwrap();
    assert_eq!(r1.status().as_u16(), 200);

    let r2 = client()
        .get(format!("{}/second", server.url()))
        .send()
        .unwrap();
    assert_eq!(r2.status().as_u16(), 201);
}

#[test]
fn should_method_from_when_builder() {
    // should_method is available on WhenWhyhttpRequest
    let server = Whyhttp::run();
    server
        .when()
        .path("/post-only")
        .should_method("POST")
        .response()
        .status(200u16);

    client()
        .post(format!("{}/post-only", server.url()))
        .send()
        .unwrap();
}

#[test]
fn response_status_from_when_builder() {
    // response_status is available on WhenWhyhttpRequest
    let server = Whyhttp::run();
    server.when().path("/created").response_status(201u16);

    let resp = client()
        .get(format!("{}/created", server.url()))
        .send()
        .unwrap();
    assert_eq!(resp.status().as_u16(), 201);
}

#[test]
fn response_body_from_should_builder() {
    // response_body is available on ShouldWhyhttpRequest
    let server = Whyhttp::run();
    server.when().path("/msg").should().response_body("ok");

    let resp = client()
        .get(format!("{}/msg", server.url()))
        .send()
        .unwrap();
    assert_eq!(resp.text().unwrap(), "ok");
}

#[test]
fn when_path_from_should_builder() {
    // when_path available on ShouldWhyhttpRequest — starts a new expectation
    let server = Whyhttp::run();
    server
        .when_path("/a")
        .should()
        .when_path("/b") // ← called on ShouldWhyhttpRequest
        .response()
        .status(201u16);

    client().get(format!("{}/a", server.url())).send().unwrap();
    client().get(format!("{}/b", server.url())).send().unwrap();
}
